modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 2.1"

[[mods]]
modId = "bacillus"
version = "${version}"
displayName = "Bacillus"
authors = "Logan McLean (ttttdoy), Miko Elbrecht (ATPStorages)"
description = '''
A rewrite of the original Bacteria mod by TeNNoX.
http://tennoxmods.blogspot.com/p/bacteria-mod.html

Textures from the Bacterium mod for 1.20.1 by InEqualMeasure.
https://www.curseforge.com/minecraft/mc-mods/bacterium
'''
logoFile = "assets/bacillus/icon.png"

[[dependencies.bacillus]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bacillus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bacillus]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bacillus]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bacillus.mixins.json"