modLoader = "kotlinforforge"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 2.1"

[[mods]]
modId = "bacillus"
version = "${version}"
displayName = "Bacillus"
authors = ""
description = '''
Textures from the Bacterium mod for 1.20.1 by InEqualMeasure.
https://www.curseforge.com/minecraft/mc-mods/bacterium

Original Bacteria mod by TeNNoX.
http://tennoxmods.blogspot.com/p/bacteria-mod.html
'''
logoFile = "../assets/bacillus/icon.png"

[[dependencies.bacillus]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bacillus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bacillus]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

