modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 2.1"

[[mods]]
modId = "bacterium"
version = "${version}"
displayName = "bacterium"
authors = ""
description = '''
Port of the Bacterium mod for 1.20.1 by InEqualMeasure.
https://www.curseforge.com/minecraft/mc-mods/bacterium

Original mod by TeNNoX.
http://tennoxmods.blogspot.com/p/bacteria-mod.html
'''
logoFile = "assets/bacterium/icon.png"

[[dependencies.bacterium]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bacterium]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bacterium]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

